Repository DasithKuruppu/uglyBot, pull requests merged in 2022-10, with the labels that each got.

#49 feat(provisioned concurrency #41): Added in provisioned concurrency
  pulumi/lambdas/discordEventsProcessor.ts
  pulumi/lambdas/httpEventsProcessor.ts
Labels: bug, enhancement

#60 feat(inviteLink #59): Users are now able request invite links
  bot/interactions/commands/request/index.ts
  bot/interactions/commands/request/inviteLink.ts
  bot/interactions/commands/request/role.ts
  bot/registerCommands/commands.ts
Labels: enhancement

#69 fix(Typos in artifacts #70): Update Artifact Names
  bot/embeds/templates/artifactsList.ts
Labels: bug
